//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InovatecDBEntities : DbContext
    {
        public InovatecDBEntities()
            : base("name=InovatecDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_application> tb_application { get; set; }
        public virtual DbSet<tb_application_log> tb_application_log { get; set; }
        public virtual DbSet<tb_service> tb_service { get; set; }
        public virtual DbSet<tb_service_log> tb_service_log { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
    
        public virtual ObjectResult<TestProcedura_Result> TestProcedura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestProcedura_Result>("TestProcedura");
        }
    }
}
