//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_service_log
    {
        public int id { get; set; }
        public int service_id { get; set; }
        public System.DateTime date { get; set; }
        public bool status { get; set; }
    
        public virtual tb_service tb_service { get; set; }
    }
}
