//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotification
    {
        public int id { get; set; }
        public string MailedTo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Message { get; set; }
        public bool IsSent { get; set; }
        public System.DateTime SentOn { get; set; }
    }
}
