#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Inovatec_process_tracker.Resource", IsApplication=true)]

namespace Inovatec_process_tracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int Main_btnServices = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int Services_Service1_ServiceInfo_btnCancel = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int Services_Service1_ServiceInfo_btnOk = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int Services_Service1_ServiceInfo_datePicker = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int Services_Service1_btnRefresh = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Services_Service1_btnServiceInfo = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int Services_Service1_txtStatus = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int Services_Service1_txtTitle = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Services_btnService1 = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int Servuces_Service1_ServiceInfo_txtTitle = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int btnApplications = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int linearLayout1 = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int txtChooseAction = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int txtMainWelcome = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int txtTitle = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Services = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Services_Service1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Services_Service1_ServiceInfo = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
